modLoader = "javafml"
loaderVersion = "[46,)"
license = "All Rights Reserved"
issueTrackerURL="https://github.com/CorgiTaco/World-Viewer-2/issues" #optional
[[mods]] #mandatory
modId = "worldviewer" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "${mod_name}" #mandatory
logoFile = "multiloader.png" #optional (needs to be in the root of your mod jar (root of your 'resources' folder))
credits = "Thanks for this example mod goes to Java" #optional
authors = "${mod_author}" #optional
description = '''
This is a long form description of the mod. You can write whatever you want here
''' #mandatory (Supports multiline text)

[[dependencies.worldviewer]] #optional
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.worldviewer]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.worldviewer]]
modId = "corgilib"
mandatory = true
versionRange = "[4.0.0.0,)"
ordering = "NONE"
side = "BOTH"
